apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  # Changed from NodePort to ClusterIP.
  # This makes the service only reachable from within the cluster.
  type: ClusterIP
  selector:
    # This selector must match the labels on your pods (from deployment.yaml)
    app: wisecow
  ports:
    - protocol: TCP
      # The port the service will be available on inside the cluster.
      port: 4499
      # The port on the container that this service will forward traffic to.
      targetPort: 4499

